name = "ExactReals"
uuid = "cc8eb9ea-40c6-483d-ae01-5f60885b8dd9"
authors = ["David P. Sanders"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
